default:
  image: $CI_REGISTRY/leuen4/container_builder/speki-ci

stages:
  - build
  - test
  - doc

build:
  stage: build
  script: make
  artifacts:
    paths:
      - ./bin

test:
  stage: test
  script: make test
  artifacts:
    when: always
    reports:
      junit: 
        - ./cppcheck_junit.xml
        - ./doxy_junit.xml

pages:
  stage: doc
  script: |
    make doc
    mv ./doc/doxygen/html public
  artifacts:
    paths:
      - public
  only:
    - master
    - doc
