version: '3'
services:
  carme-docker:
    build:
      context: .
      dockerfile: Dockerfile
    # Add hostname so that bash shows a nice name.
    hostname: carme-docker
    # Add hostfile entry for easy access to WSL host ip.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Forward ST-Link v2 JTAG USB to container and allow hotplug.
      - /dev:/dev
      # Where VS Code mounts the folder of the project
      - ..:/workspace/speki:cached
    # https://stackoverflow.com/questions/24225647/docker-a-way-to-give-access-to-a-host-usb-or-serial-device
    # http://marc.merlins.org/perso/linux/post_2018-12-20_Accessing-USB-Devices-In-Docker-_ttyUSB0_-dev-bus-usb-_-for-fastboot_-adb_-without-using-privileged.html
    device_cgroup_rules:
      - 'c 189:* rmw'
    # Keep container running
    command: /bin/sh -c "while sleep 1000; do :; done"
    # CGroups dont work for the moment. Force priviledged mode.
    privileged: true
